---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "argocd"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "deployment-1"
  namespace: "argocd"
  labels:
    amit: "deployment-ns"
spec:
  replicas: 3
  selector:
    matchLabels:
      amit: "deployment-ns"
  template:
    metadata:
      labels:
        amit: "deployment-ns"
    spec:
      containers:
      - name: "nginx-1"
        image: "nginx:latest"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "deployment-1-hpa-gpro"
  namespace: "argocd"
  labels:
    amit: "deployment-ns"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "deployment-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "deployment-1-service"
  namespace: "argocd"
  labels:
    amit: "deployment-ns"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8081
  selector:
    amit: "deployment-ns"
  type: "LoadBalancer"
  loadBalancerIP: ""
