# Frontend Configuration
frontend:
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.23"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    host: "app.example.com"
    className: "nginx"

# Backend Configuration
backend:
  replicaCount: 3
  image:
    repository: myorg/node-api
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
  environment:
    DB_HOST: "postgres-service"
    DB_PORT: "5432"

# Database Configuration
database:
  image:
    repository: postgres
    tag: "15-alpine"
  storage:
    size: 10Gi
    storageClass: "standard"
  credentials:
    username: "admin"
    password: "securepassword123"