apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    app: backend
    tier: api
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 3000
  type: {{ .Values.backend.service.type }}