apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-creds
type: Opaque
data:
  username: {{ .Values.database.credentials.username | b64enc }}
  password: {{ .Values.database.credentials.password | b64enc }}